server:
  port: 80


eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

spring:
  application:
    name: springcloud-order-openfegin-service

#超时设置 默认为1秒，请求超时直接报错。
ribbon:
  ReadTimeout:  5000 #建立连接后读取到可用资源所需时间
  ConnectTimeout: 5000 #建立连接的时间


#feign日志以什么级别监控哪个接口
logging:
  level:
    com.atguigu.springcloud.service.PaymentFeignService: debug

