server:
  port: 80


eureka:
  client:
    register-with-eureka: false    #表识不向注册中心注册自己
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

#超时设置 默认为1秒，请求超时直接报错。
ribbon:
  ReadTimeout:  5000 #建立连接后读取到可用资源所需时间
  ConnectTimeout: 5000 #建立连接的时间

spring:
  application:
    name: springcloud-consumer-hystrix-order

feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。
